# .github/workflows/pages-build-deployment.yml
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages-v2        # <-- change this string
  cancel-in-progress: true
